[View in Colaboratory](https://colab.research.google.com/github/JacksonIsaac/colab_notebooks/blob/master/Chap1_machine_learning_in_action.ipynb)

# Machine Learning in Action
## Chapter 1

### Training data set layout

x -> Features / Independent variables

y -> Label / dependent variable


![Features and Target Variable](https://www.safaribooksonline.com/library/view/machine-learning-in/9781617290183/01fig02_alt.jpg)

### Supervised and Un-supervised tasks

Supervised -> Classification, Prediction, etc.

Un-supervised -> Clustering

![Machine Learning tasks](https://i.imgur.com/zs3wtMT.png)

### Numpy Array and matrix

In [0]:
import numpy as np

Create a 4x4 array of random numbers

In [2]:
np.random.rand(4, 4)

array([[0.30152241, 0.71945387, 0.75783614, 0.2012428 ],
       [0.50943159, 0.11033032, 0.90467055, 0.53723346],
       [0.06136372, 0.1791022 , 0.21583837, 0.03556322],
       [0.33831625, 0.87309895, 0.21208185, 0.4107346 ]])

We use mat() function to convert an array into matrix

In [0]:
rand_mat = np.mat(np.random.rand(4, 4))

In [4]:
rand_mat

matrix([[0.70874345, 0.68426487, 0.88454942, 0.51133547],
        [0.52549947, 0.23607762, 0.66783886, 0.0502207 ],
        [0.03239565, 0.87873196, 0.89867317, 0.8936896 ],
        [0.13224244, 0.25796219, 0.77466257, 0.15579848]])

Computing Inverse of a matrix using .I operator

In [5]:
rand_mat.I

matrix([[  25.24473466,  -36.5260936 ,  -16.11491489,   21.3581649 ],
        [-122.23279987,  189.0456903 ,   79.46478513, -115.59094195],
        [  15.55130957,  -24.5674163 ,  -10.45298492,   16.83957764],
        [ 103.63386078, -159.85318126,  -65.92040031,   95.94860093]])

In [6]:
rand_mat * rand_mat.I

matrix([[ 1.00000000e+00, -1.41617382e-14, -1.11515828e-14,
          1.65536760e-14],
        [ 9.91780548e-15,  1.00000000e+00, -5.56801923e-15,
          1.21778245e-14],
        [ 2.07320530e-14, -1.09165986e-14,  1.00000000e+00,
          1.03478845e-14],
        [ 4.61186712e-15, -3.22148221e-15, -1.96192866e-15,
          1.00000000e+00]])

Using eye() to create identity matrix

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
(rand_mat * rand_mat.I) - np.eye(4)

matrix([[ 1.08801856e-14, -1.41617382e-14, -1.11515828e-14,
          1.65536760e-14],
        [ 9.91780548e-15, -1.32116540e-14, -5.56801923e-15,
          1.21778245e-14],
        [ 2.07320530e-14, -1.09165986e-14, -1.74305015e-14,
          1.03478845e-14],
        [ 4.61186712e-15, -3.22148221e-15, -1.96192866e-15,
          4.88498131e-15]])